/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mainapp;

import javax.swing.text.MaskFormatter;
import javax.swing.text.DefaultFormatterFactory;
import java.text.ParseException;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.Color;
import javax.swing.BorderFactory;

/**
 *
 * @author trank
 */
public class moduleSettings extends javax.swing.JFrame {

    /**
     * Creates new form newModulePop
     */
    private java.awt.Window caller;

    public moduleSettings() {
        setUndecorated(true);
        initComponents();
        setupDateFields();
        setLocationRelativeTo(null);
    }

    public moduleSettings(java.awt.Window caller) {
        this.caller = caller;
        caller.setEnabled(false);
        setUndecorated(true);
        initComponents();
        setupDateFields();
        setLocationRelativeTo(null);
    }

    @Override
    public void dispose() {
        if (caller != null) caller.setEnabled(true);
        super.dispose();
    }

    private void setupDateFields() {
        try {
            MaskFormatter mask1 = new MaskFormatter("##/##/####");
            mask1.setPlaceholderCharacter('_');
            MaskFormatter mask2 = new MaskFormatter("##/##/####");
            mask2.setPlaceholderCharacter('_');

            afterPeriodFTF.setFormatterFactory(new DefaultFormatterFactory(mask1));
            beforePeriodFTF.setFormatterFactory(new DefaultFormatterFactory(mask2));
        } catch (ParseException e) {
            e.printStackTrace();
        }

        updateButton.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                String title = titleTF.getText().trim();
                String startDate = beforePeriodFTF.getText().trim();
                String endDate = afterPeriodFTF.getText().trim();

                if (title.isEmpty()) {
                    javax.swing.JOptionPane.showMessageDialog(null, "Title cannot be empty.");
                    return;
                }
                if (!isDateValid(beforePeriodFTF) || !isDateValid(afterPeriodFTF)) {
                    javax.swing.JOptionPane.showMessageDialog(null, "Dates must be valid and not before today.");
                    return;
                }

                try {
                    ModuleStorage.saveModule(new ModuleStorage.Module(title, startDate, endDate, "0"));
                    javax.swing.JOptionPane.showMessageDialog(null, "Module \"" + title + "\" created successfully!");                    
                    moduleSettings secondWindow = new moduleSettings(); 
                    secondWindow.setVisible(true); 
                    dispose(); 
                } catch (Exception ex) {
                    javax.swing.JOptionPane.showMessageDialog(null, "Failed to save module: " + ex.getMessage(), "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
                }
            }
        });
    }

    private boolean isDateValid(javax.swing.JFormattedTextField field) {
        String text = field.getText().replace("_", "").trim();
        try {
            DateTimeFormatter fmt = DateTimeFormatter.ofPattern("MM/dd/yyyy");
            LocalDate entered = LocalDate.parse(text, fmt);
            return !entered.isBefore(LocalDate.now());
        } catch (Exception e) {
            return false;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        periodLabel = new javax.swing.JLabel();
        returnButton = new javax.swing.JLabel();
        updateButton = new javax.swing.JLabel();
        titleTF = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        afterPeriodFTF = new javax.swing.JFormattedTextField();
        beforePeriodFTF = new javax.swing.JFormattedTextField();
        dashLabel = new javax.swing.JLabel();
        createButton = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        moduleLabel = new javax.swing.JLabel();
        subModuleLabel = new javax.swing.JLabel();
        sTitleLabel = new javax.swing.JLabel();
        subModCB = new javax.swing.JComboBox<>();
        subModNameLabel = new javax.swing.JLabel();
        subModNameTF = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        mainPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        titleLabel.setText("Title:   ");

        periodLabel.setText("Period:");

        returnButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        returnButton.setText("Return");
        returnButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        returnButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                returnButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                returnButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                returnButtonMouseExited(evt);
            }
        });

        updateButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        updateButton.setText("Update");
        updateButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        updateButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updateButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                updateButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                updateButtonMouseExited(evt);
            }
        });

        titleTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                titleTFActionPerformed(evt);
            }
        });

        afterPeriodFTF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        afterPeriodFTF.setText("__/__/____");
        afterPeriodFTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                afterPeriodFTFActionPerformed(evt);
            }
        });

        beforePeriodFTF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        beforePeriodFTF.setText("__/__/____");
        beforePeriodFTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                beforePeriodFTFActionPerformed(evt);
            }
        });

        dashLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dashLabel.setText("-");

        createButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        createButton.setText("Create S-Module");
        createButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        createButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                createButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                createButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                createButtonMouseExited(evt);
            }
        });

        moduleLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        moduleLabel.setText("Module Settings");

        subModuleLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        subModuleLabel.setText("Sub-Module Settings");

        sTitleLabel.setText("Sub-Module:");

        subModCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        subModNameLabel.setText("Label:");

        subModNameTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subModNameTFActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 358, Short.MAX_VALUE)
            .addComponent(jSeparator2)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(subModNameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(subModNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72))
            .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(mainPanelLayout.createSequentialGroup()
                    .addGap(32, 32, 32)
                    .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(mainPanelLayout.createSequentialGroup()
                            .addGap(36, 36, 36)
                            .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(titleTF, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                            .addComponent(periodLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(beforePeriodFTF, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(dashLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(afterPeriodFTF, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(mainPanelLayout.createSequentialGroup()
                    .addGap(25, 25, 25)
                    .addComponent(updateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(15, 15, 15)
                    .addComponent(createButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(15, 15, 15)
                    .addComponent(returnButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(mainPanelLayout.createSequentialGroup()
                    .addGap(135, 135, 135)
                    .addComponent(moduleLabel))
                .addGroup(mainPanelLayout.createSequentialGroup()
                    .addGap(120, 120, 120)
                    .addComponent(subModuleLabel))
                .addGroup(mainPanelLayout.createSequentialGroup()
                    .addGap(55, 55, 55)
                    .addComponent(sTitleLabel)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(subModCB, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(moduleLabel)
                .addGap(10, 10, 10)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titleTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(titleLabel))
                .addGap(15, 15, 15)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(periodLabel)
                    .addComponent(beforePeriodFTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dashLabel)
                    .addComponent(afterPeriodFTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(subModuleLabel)
                .addGap(10, 10, 10)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sTitleLabel)
                    .addComponent(subModCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(subModNameLabel)
                    .addComponent(subModNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(returnButton, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(createButton, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void titleTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_titleTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_titleTFActionPerformed

    private void updateButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateButtonMouseEntered
        // TODO add your handling code here:
        updateButton.setBackground(Color.white);
        updateButton.setForeground(Color.white); 
        updateButton.setBorder(BorderFactory.createLineBorder(Color.WHITE));
    }//GEN-LAST:event_updateButtonMouseEntered

    private void updateButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateButtonMouseExited
        // TODO add your handling code here:
        updateButton.setBackground(new Color(153,153,153));
        updateButton.setForeground(Color.black); 
        updateButton.setBorder(BorderFactory.createLineBorder(Color.black));
    }//GEN-LAST:event_updateButtonMouseExited

    private void returnButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_returnButtonMouseEntered
        // TODO add your handling code here:
        returnButton.setBackground(Color.white);
        returnButton.setForeground(Color.white); 
        returnButton.setBorder(BorderFactory.createLineBorder(Color.WHITE));
    }//GEN-LAST:event_returnButtonMouseEntered

    private void returnButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_returnButtonMouseExited
        // TODO add your handling code here:
        returnButton.setBackground(new Color(153,153,153));
        returnButton.setForeground(Color.black); 
        returnButton.setBorder(BorderFactory.createLineBorder(Color.black));
    }//GEN-LAST:event_returnButtonMouseExited

    private void returnButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_returnButtonMouseClicked
        // TODO add your handling code here:
        viewModule secondWindow = new viewModule(); 
        secondWindow.setVisible(true); 
        super.dispose();
    }//GEN-LAST:event_returnButtonMouseClicked

    private void createButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_createButtonMouseEntered
        // TODO add your handling code here:
        createButton.setBackground(Color.white);
        createButton.setForeground(Color.white); 
        createButton.setBorder(BorderFactory.createLineBorder(Color.WHITE));
    }//GEN-LAST:event_createButtonMouseEntered

    private void createButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_createButtonMouseExited
        // TODO add your handling code here:
        createButton.setBackground(new Color(153,153,153));
        createButton.setForeground(Color.black); 
        createButton.setBorder(BorderFactory.createLineBorder(Color.black));
    }//GEN-LAST:event_createButtonMouseExited

    private void afterPeriodFTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_afterPeriodFTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_afterPeriodFTFActionPerformed

    private void beforePeriodFTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_beforePeriodFTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_beforePeriodFTFActionPerformed

    private void subModNameTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subModNameTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_subModNameTFActionPerformed

    private void createButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_createButtonMouseClicked
        // TODO add your handling code here:
        createSubModule secondWindow = new createSubModule(this);
        secondWindow.setVisible(true); 
    }//GEN-LAST:event_createButtonMouseClicked

    private void updateButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateButtonMouseClicked
        // TODO add your handling code here:
        
        // Logic goes here
        
        // update my disposing and setting it visible again
    }//GEN-LAST:event_updateButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(moduleSettings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(moduleSettings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(moduleSettings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(moduleSettings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new moduleSettings().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField afterPeriodFTF;
    private javax.swing.JFormattedTextField beforePeriodFTF;
    private javax.swing.JLabel createButton;
    private javax.swing.JLabel dashLabel;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JLabel moduleLabel;
    private javax.swing.JLabel periodLabel;
    private javax.swing.JLabel returnButton;
    private javax.swing.JLabel sTitleLabel;
    private javax.swing.JComboBox<String> subModCB;
    private javax.swing.JLabel subModNameLabel;
    private javax.swing.JTextField subModNameTF;
    private javax.swing.JLabel subModuleLabel;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JTextField titleTF;
    private javax.swing.JLabel updateButton;
    // End of variables declaration//GEN-END:variables
}
