/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mainapp;
import javax.swing.*;
import javax.swing.text.*;
import javax.swing.UIDefaults;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.awt.event.*;
import java.io.*;
import java.io.File;

/**
 *
 * @author trank
 */
public class OptionsMenu extends javax.swing.JFrame {

    private static final String STATS_FILE = System.getProperty("user.dir") + File.separator + "TypeMania_stats.txt";

    /**
     * Creates new form MainMenu
     */
    public OptionsMenu() {
        setUndecorated(true);  // Remove title bar
        initComponents();
        setLocationRelativeTo(null);  // Center on screen
        addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowOpened(java.awt.event.WindowEvent e) {
                toFront();
                requestFocus();
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titlePanel = new javax.swing.JPanel();
        gameIcon = new javax.swing.JLabel();
        gameTitle = new javax.swing.JLabel();
        optionPanel = new javax.swing.JPanel();
        createModelPanel = new javax.swing.JPanel();
        createModelButton = new javax.swing.JLabel();
        returnPanel = new javax.swing.JPanel();
        returnButton = new javax.swing.JLabel();
        viewModulesPanel = new javax.swing.JPanel();
        viewModulesButton = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        titlePanel.setBackground(new java.awt.Color(153, 153, 153));
        titlePanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        titlePanel.setPreferredSize(new java.awt.Dimension(235, 300));

        gameIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/calendarIcon.png"))); // NOI18N

        gameTitle.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        gameTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        gameTitle.setText("SCHEDULE");

        javax.swing.GroupLayout titlePanelLayout = new javax.swing.GroupLayout(titlePanel);
        titlePanel.setLayout(titlePanelLayout);
        titlePanelLayout.setHorizontalGroup(
            titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, titlePanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(gameIcon)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, titlePanelLayout.createSequentialGroup()
                .addContainerGap(41, Short.MAX_VALUE)
                .addComponent(gameTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
        );
        titlePanelLayout.setVerticalGroup(
            titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titlePanelLayout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(gameIcon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(gameTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(86, Short.MAX_VALUE))
        );

        optionPanel.setBackground(new java.awt.Color(51, 51, 51));
        optionPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        optionPanel.setForeground(new java.awt.Color(255, 255, 255));
        optionPanel.setPreferredSize(new java.awt.Dimension(235, 300));

        createModelButton.setBackground(new java.awt.Color(153, 153, 153));
        createModelButton.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        createModelButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        createModelButton.setText("CREATE MODULE");
        createModelButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        createModelButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                createModelButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                createModelButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                createModelButtonMouseExited(evt);
            }
        });

        javax.swing.GroupLayout createModelPanelLayout = new javax.swing.GroupLayout(createModelPanel);
        createModelPanel.setLayout(createModelPanelLayout);
        createModelPanelLayout.setHorizontalGroup(
            createModelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(createModelButton, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
        );
        createModelPanelLayout.setVerticalGroup(
            createModelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(createModelButton, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
        );

        returnButton.setBackground(new java.awt.Color(153, 153, 153));
        returnButton.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        returnButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        returnButton.setText("RETURN TO MENU");
        returnButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        returnButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                returnButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                returnButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                returnButtonMouseExited(evt);
            }
        });

        javax.swing.GroupLayout returnPanelLayout = new javax.swing.GroupLayout(returnPanel);
        returnPanel.setLayout(returnPanelLayout);
        returnPanelLayout.setHorizontalGroup(
            returnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(returnButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        returnPanelLayout.setVerticalGroup(
            returnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(returnButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
        );

        viewModulesPanel.setPreferredSize(new java.awt.Dimension(28, 25));

        viewModulesButton.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        viewModulesButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        viewModulesButton.setText("VIEW MODULES");
        viewModulesButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        viewModulesButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewModulesButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                viewModulesButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                viewModulesButtonMouseExited(evt);
            }
        });

        javax.swing.GroupLayout viewModulesPanelLayout = new javax.swing.GroupLayout(viewModulesPanel);
        viewModulesPanel.setLayout(viewModulesPanelLayout);
        viewModulesPanelLayout.setHorizontalGroup(
            viewModulesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(viewModulesButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        viewModulesPanelLayout.setVerticalGroup(
            viewModulesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(viewModulesButton, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout optionPanelLayout = new javax.swing.GroupLayout(optionPanel);
        optionPanel.setLayout(optionPanelLayout);
        optionPanelLayout.setHorizontalGroup(
            optionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, optionPanelLayout.createSequentialGroup()
                .addContainerGap(57, Short.MAX_VALUE)
                .addGroup(optionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(createModelPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(returnPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(viewModulesPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE))
                .addGap(56, 56, 56))
        );
        optionPanelLayout.setVerticalGroup(
            optionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(optionPanelLayout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addComponent(createModelPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(viewModulesPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(returnPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(102, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(titlePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(optionPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(optionPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE)
            .addComponent(titlePanel, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void createModelButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_createModelButtonMouseEntered
        // TODO add your handling code here:
        createModelButton.setBackground(Color.white);
        createModelButton.setForeground(Color.white); 
        createModelButton.setBorder(BorderFactory.createLineBorder(Color.WHITE));

        
    }//GEN-LAST:event_createModelButtonMouseEntered

    private void createModelButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_createModelButtonMouseExited
        // TODO add your handling code here:
        createModelButton.setBackground(new Color(153,153,153));
        createModelButton.setForeground(Color.black); 
        createModelButton.setBorder(BorderFactory.createLineBorder(Color.black));
    }//GEN-LAST:event_createModelButtonMouseExited

    private void returnButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_returnButtonMouseEntered
        // TODO add your handling code here:
        returnButton.setBackground(Color.white);
        returnButton.setForeground(Color.white); 
        returnButton.setBorder(BorderFactory.createLineBorder(Color.WHITE));
    }//GEN-LAST:event_returnButtonMouseEntered

    private void returnButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_returnButtonMouseExited
        // TODO add your handling code here:
        returnButton.setBackground(new Color(153,153,153));
        returnButton.setForeground(Color.black); 
        returnButton.setBorder(BorderFactory.createLineBorder(Color.black));
    }//GEN-LAST:event_returnButtonMouseExited

    private void returnButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_returnButtonMouseClicked
        // TODO add your handling code here:
        MainMenu secondWindow = new MainMenu(); 
        secondWindow.setVisible(true); 
        this.dispose();
    }//GEN-LAST:event_returnButtonMouseClicked

    private void createModelButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_createModelButtonMouseClicked
        // TODO add your handling code here:
        newModulePop secondWindow = new newModulePop(this);
        secondWindow.setVisible(true);
    }//GEN-LAST:event_createModelButtonMouseClicked

    private void viewModulesButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewModulesButtonMouseEntered
        // TODO add your handling code here:
        viewModulesButton.setBackground(Color.white);
        viewModulesButton.setForeground(Color.white); 
        viewModulesButton.setBorder(BorderFactory.createLineBorder(Color.WHITE));
    }//GEN-LAST:event_viewModulesButtonMouseEntered

    private void viewModulesButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewModulesButtonMouseExited
        // TODO add your handling code here:
        viewModulesButton.setBackground(new Color(153,153,153));
        viewModulesButton.setForeground(Color.black); 
        viewModulesButton.setBorder(BorderFactory.createLineBorder(Color.black));
    }//GEN-LAST:event_viewModulesButtonMouseExited

    private void viewModulesButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewModulesButtonMouseClicked
        // TODO add your handling code here:
        selectModule secondWindow = new selectModule(this);
        secondWindow.setVisible(true);
    }//GEN-LAST:event_viewModulesButtonMouseClicked

    private void showStatsDialog() {
        JDialog statsDialog = new JDialog(this, "Game Stats", true);
        statsDialog.setUndecorated(true);
        statsDialog.setSize(500, 350);
        statsDialog.setLocationRelativeTo(this);

        JPanel mainPanel = new JPanel(new BorderLayout(10, 10));
        mainPanel.setBackground(new Color(51, 51, 51));
        mainPanel.setBorder(BorderFactory.createCompoundBorder(
            BorderFactory.createLineBorder(Color.WHITE, 2),
            BorderFactory.createEmptyBorder(15, 15, 15, 15)
        ));

        // Table setup
        String[] columns = {"Date", "Time (s)", "WPM", "Accuracy %"};
        DefaultTableModel model = new DefaultTableModel(columns, 0);

        // Read stats from file
        File file = new File(STATS_FILE);
        if (file.exists()) {
            try (BufferedReader reader = new BufferedReader(new FileReader(file))) {
                String line;
                while ((line = reader.readLine()) != null) {
                    String[] parts = line.split("\\|");
                    if (parts.length == 4) {
                        model.addRow(parts);
                    }
                }
            } catch (IOException e) {
                e.printStackTrace();
            }
        }

        JTable table = new JTable(model);
        table.setBackground(new Color(30, 30, 30));
        table.setForeground(Color.WHITE);
        table.setGridColor(new Color(80, 80, 80));
        table.getTableHeader().setBackground(new Color(70, 70, 70));
        table.getTableHeader().setForeground(Color.WHITE);

        JScrollPane scrollPane = new JScrollPane(table);
        scrollPane.getViewport().setBackground(new Color(30, 30, 30));
        mainPanel.add(scrollPane, BorderLayout.CENTER);

        // Close button
        JLabel closeButton = new JLabel("CLOSE", SwingConstants.CENTER);
        closeButton.setOpaque(true);
        closeButton.setBackground(new Color(153, 153, 153));
        closeButton.setForeground(Color.BLACK);
        closeButton.setPreferredSize(new Dimension(100, 30));
        closeButton.setBorder(BorderFactory.createLineBorder(Color.BLACK, 2));
        closeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                statsDialog.dispose();
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                closeButton.setForeground(Color.WHITE);
                closeButton.setBorder(BorderFactory.createLineBorder(Color.WHITE, 2));
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                closeButton.setForeground(Color.BLACK);
                closeButton.setBorder(BorderFactory.createLineBorder(Color.BLACK, 2));
            }
        });

        JPanel buttonPanel = new JPanel(new FlowLayout(FlowLayout.CENTER));
        buttonPanel.setBackground(new Color(51, 51, 51));
        buttonPanel.add(closeButton);
        mainPanel.add(buttonPanel, BorderLayout.SOUTH);

        statsDialog.add(mainPanel);
        statsDialog.setVisible(true);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel createModelButton;
    private javax.swing.JPanel createModelPanel;
    private javax.swing.JLabel gameIcon;
    private javax.swing.JLabel gameTitle;
    private javax.swing.JPanel optionPanel;
    private javax.swing.JLabel returnButton;
    private javax.swing.JPanel returnPanel;
    private javax.swing.JPanel titlePanel;
    private javax.swing.JLabel viewModulesButton;
    private javax.swing.JPanel viewModulesPanel;
    // End of variables declaration//GEN-END:variables
}
