/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mainapp;

import java.awt.Color;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import javax.swing.BorderFactory;

/**
 *
 * @author trank
 */
public class viewModule extends javax.swing.JFrame {

    /**
     * Creates new form viewModule
     */
    
    private String moduleName;
    private int moduleID;
    private monthlyViewPanel monthly;
    private weeklyViewPanel  weekly;
    private dailyViewPanels  daily;
    
    public viewModule() {
        setUndecorated(true);
        initComponents();
        setLocationRelativeTo(null);
        addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowOpened(java.awt.event.WindowEvent e) {
                toFront();
                requestFocus();
            }
        });
    }
    
    public viewModule(int modID) {
        moduleID = modID; 
           
        setUndecorated(true);
        initComponents();
        setLocationRelativeTo(null);
        addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowOpened(java.awt.event.WindowEvent e) {
                toFront();
                requestFocus();
            }
        });
        
        try{
            moduleName = DBMethods.getModuleNameById(moduleID);
        } catch (Exception ex) {
            javax.swing.JOptionPane.showMessageDialog(null, "Failed to get module name: " + ex.getMessage(), "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
        
        changeModButton.setText(moduleName);

        // Add view panels to the CardLayout viewPanel
        monthly = new monthlyViewPanel(viewModule.this, moduleID);
        weekly  = new weeklyViewPanel(viewModule.this, moduleID);
        daily   = new dailyViewPanels(viewModule.this, moduleID);
        viewPanel.add(monthly, "Monthly");
        viewPanel.add(weekly,  "Weekly");
        viewPanel.add(daily,   "Daily");

        // Switch cards when the combo box changes; reload the selected panel
        typeCB.addActionListener(e -> {
            String selected = (String) typeCB.getSelectedItem();
            if (selected != null) {
                ((java.awt.CardLayout) viewPanel.getLayout()).show(viewPanel, selected);
                if ("Monthly".equals(selected))     monthly.loadMonth();
                else if ("Weekly".equals(selected)) weekly.loadWeek();
                else if ("Daily".equals(selected))  daily.loadDay();
            }
        });

        // Show monthly by default
        ((java.awt.CardLayout) viewPanel.getLayout()).show(viewPanel, "Monthly");

        // Repurpose the unused timeLabel as a "Today" button that opens dayModel
        timeLabel.setText("Today");
        timeLabel.setBorder(BorderFactory.createLineBorder(Color.black));
        timeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        timeLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                String today = LocalDate.now().format(DateTimeFormatter.ofPattern("MM/dd/yyyy"));
                dayModel dm = new dayModel(viewModule.this, moduleID, today, () -> reloadCurrentView());
                dm.setVisible(true);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                timeLabel.setBackground(Color.white);
                timeLabel.setForeground(Color.white);
                timeLabel.setBorder(BorderFactory.createLineBorder(Color.WHITE));
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                timeLabel.setBackground(new Color(153, 153, 153));
                timeLabel.setForeground(Color.black);
                timeLabel.setBorder(BorderFactory.createLineBorder(Color.black));
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public void reloadCurrentView() {
        String selected = (String) typeCB.getSelectedItem();
        if ("Monthly".equals(selected) && monthly != null)    monthly.loadMonth();
        else if ("Weekly".equals(selected) && weekly != null) weekly.loadWeek();
        else if ("Daily".equals(selected) && daily != null)   daily.loadDay();
    }

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        optionsPanel = new javax.swing.JPanel();
        viewPanel = new javax.swing.JPanel();
        typeLabel = new javax.swing.JLabel();
        typeCB = new javax.swing.JComboBox<>();
        typeTitleLabel = new javax.swing.JLabel();
        timeLabel = new javax.swing.JLabel();
        mmButton = new javax.swing.JLabel();
        changeModButton = new javax.swing.JLabel();
        settingsButton = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        optionsPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        viewPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        viewPanel.setLayout(new java.awt.CardLayout());

        typeLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        typeLabel.setText("View Type:");

        typeCB.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        typeCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Monthly", "Weekly", "Daily" }));

        typeTitleLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        typeTitleLabel.setText("Type Label");

        timeLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        timeLabel.setText("Time");

        mmButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        mmButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mmButton.setText("Main Menu");
        mmButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        mmButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mmButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mmButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mmButtonMouseExited(evt);
            }
        });

        changeModButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        changeModButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        changeModButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        changeModButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                changeModButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                changeModButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                changeModButtonMouseExited(evt);
            }
        });

        settingsButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        settingsButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        settingsButton.setText("Module Settings");
        settingsButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        settingsButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                settingsButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                settingsButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                settingsButtonMouseExited(evt);
            }
        });

        javax.swing.GroupLayout optionsPanelLayout = new javax.swing.GroupLayout(optionsPanel);
        optionsPanel.setLayout(optionsPanelLayout);
        optionsPanelLayout.setHorizontalGroup(
            optionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(optionsPanelLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(viewPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 636, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
            .addGroup(optionsPanelLayout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addComponent(mmButton, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(settingsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72)
                .addComponent(changeModButton, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(115, 115, 115))
            .addGroup(optionsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(typeLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(typeCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(154, 154, 154)
                .addComponent(typeTitleLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(timeLabel)
                .addGap(144, 144, 144))
        );
        optionsPanelLayout.setVerticalGroup(
            optionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(optionsPanelLayout.createSequentialGroup()
                .addGroup(optionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(optionsPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(optionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(typeLabel)
                            .addComponent(typeCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(optionsPanelLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(optionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(typeTitleLabel)
                            .addComponent(timeLabel))))
                .addGap(20, 20, 20)
                .addComponent(viewPanel, 200, 460, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(optionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(settingsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mmButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(changeModButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(optionsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(optionsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mmButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mmButtonMouseEntered
        // TODO add your handling code here:
        mmButton.setBackground(Color.white);
        mmButton.setForeground(Color.white);
        mmButton.setBorder(BorderFactory.createLineBorder(Color.WHITE));
    }//GEN-LAST:event_mmButtonMouseEntered

    private void mmButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mmButtonMouseExited
        // TODO add your handling code here:
        mmButton.setBackground(new Color(153,153,153));
        mmButton.setForeground(Color.black);
        mmButton.setBorder(BorderFactory.createLineBorder(Color.black));
    }//GEN-LAST:event_mmButtonMouseExited

    private void changeModButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_changeModButtonMouseEntered
        // TODO add your handling code here:
        changeModButton.setText("Change?"); 
        changeModButton.setBackground(Color.white);
        changeModButton.setForeground(Color.white);
        changeModButton.setBorder(BorderFactory.createLineBorder(Color.WHITE));
    }//GEN-LAST:event_changeModButtonMouseEntered

    private void changeModButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_changeModButtonMouseExited
        // TODO add your handling code here:
        changeModButton.setText(moduleName);
        changeModButton.setBackground(new Color(153,153,153));
        changeModButton.setForeground(Color.black);
        changeModButton.setBorder(BorderFactory.createLineBorder(Color.black));
    }//GEN-LAST:event_changeModButtonMouseExited

    private void settingsButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_settingsButtonMouseEntered
        // TODO add your handling code here:
        settingsButton.setBackground(Color.white);
        settingsButton.setForeground(Color.white);
        settingsButton.setBorder(BorderFactory.createLineBorder(Color.WHITE));
    }//GEN-LAST:event_settingsButtonMouseEntered

    private void settingsButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_settingsButtonMouseExited
        // TODO add your handling code here:
        settingsButton.setBackground(new Color(153,153,153));
        settingsButton.setForeground(Color.black);
        settingsButton.setBorder(BorderFactory.createLineBorder(Color.black));
    }//GEN-LAST:event_settingsButtonMouseExited

    private void mmButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mmButtonMouseClicked
        // TODO add your handling code here:
        MainMenu secondWindow = new MainMenu(); 
        secondWindow.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_mmButtonMouseClicked

    private void changeModButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_changeModButtonMouseClicked
        // TODO add your handling code here:
        selectModule secondWindow = new selectModule(this); 
        secondWindow.setVisible(true); 
    }//GEN-LAST:event_changeModButtonMouseClicked

    private void settingsButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_settingsButtonMouseClicked
        // TODO add your handling code here:
        moduleSettings secondWindow = new moduleSettings(moduleID); 
        secondWindow.setVisible(true); 
        this.dispose(); 
    }//GEN-LAST:event_settingsButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(viewModule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(viewModule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(viewModule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(viewModule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new viewModule().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel changeModButton;
    private javax.swing.JLabel mmButton;
    private javax.swing.JPanel optionsPanel;
    private javax.swing.JLabel settingsButton;
    private javax.swing.JLabel timeLabel;
    private javax.swing.JComboBox<String> typeCB;
    private javax.swing.JLabel typeLabel;
    private javax.swing.JLabel typeTitleLabel;
    private javax.swing.JPanel viewPanel;
    // End of variables declaration//GEN-END:variables
}
